### ISSUE TITLE
bug in event_rating view

### ISSUE THREAD

**Issue by joto** [nevs/pentabarf#15]

**Comment by joto** [comment]
pentabarf / sql / views / event_rating.sql:

where clause is wrong. it says:
WHERE
    NOT EXISTS( SELECT 1 FROM event_rating_remark WHERE event_rating_remark.event_id = event_rating.event_id ) AND
    NOT EXISTS( SELECT 1 FROM event_rating_remark WHERE event_rating_remark.person_id = event_rating.person_id )

instead it should be
WHERE
    NOT EXISTS( SELECT 1 FROM event_rating_remark WHERE event_rating_remark.event_id = event_rating.event_id AND
     event_rating_remark.person_id = event_rating.person_id )

Currently ratings don't show up if the rating doesn't have a remark but there are other ratings of the same person which have a remark. The changes above should fix this.

**Comment by nevs** [comment]
fixed in master
