### ISSUE TITLE
mail to all speakers broken

### ISSUE THREAD

**Issue by joto** [nevs/pentabarf#16]
Mail to all speakers doesn't work. In pentabarf_controller.rb the line

variables = ['email','name','person_id','conference_acronym','conference_title']

wants several attributes, but the view 'mail_all_speakers' doesn't provide the conferece_\* attributes. The 'mail_accepted_speakers' view has those attributes. The 'mail_all_reviewer' view ist also missing those fields.

**Comment by nevs** [comment]
Which version are you using? This is fixed in the latest version.
